var blogProjects = [

  {
    title:       'Baseball Ipsum',
    category:    'sports',
    author:      'Felix Hernandez',
    authorUrl:   'http://www.baseball-reference.com/players/h/hernafe02.shtml',
    publishedOn: '2015-11-04',
    body:        '<p>Baseball ipsum dolor sit amet base on balls full count leadoff. National pastime stance pine tar dribbler rookie dodgers hardball plate. <img src="http://lorempixel.com/400/200/" class="pull-left" >Club sidearm shift red sox ground rule double, left fielder pennant good eye rubber game. Steal petey center field blue wins arm visitors. Out rope base cookie grass bandbox error. Tag pennant designated hitter relief pitcher triple-A alley on deck baseball.</p><p>Dribbler left on base arm curve bag, slider around the horn disabled list. Pennant catcher gapper rope screwball home cork foul. Nubber slide rake relief pitcher wrigley choke up cup of coffee cycle bench. Loss strikeout bandbox cardinals second base practice gap center fielder. Screwball fielder\'s choice play baseline rubber game warning track bleeder. Mustard inning in the hole astroturf alley fielder\'s choice left fielder.</p><p>Home grand slam suicide squeeze breaking ball batter\'s box flyout starting pitcher. Baseball card basehit double switch save batting average losses tossed umpire batter\'s box. Shift league 4-6-3 no-hitter yankees, bleeder mound defensive indifference shutout. Squeeze mound butcher boy loss rip chin music cracker jack. Scorecard all-star helmet practice defensive indifference pull mound around the horn. Earned run relay curve full count fall classic pinch hitter helmet cheese outfielder.</p><p>Foul pitchout moneyball all-star runs left on base fielder\'s choice. Sport pine tar fair dead ball era season rip no-hitter friendly confines. Baseball card no-hitter fenway line drive left field earned run sport bush league. Tossed walk off dodgers error streak, center fielder tossed chin music. Grounder friendly confines mustard center field bandbox pinch runner cookie. Alley left on base bat second baseman passed ball foul error cy young.</p><p>No-hitter breaking ball stadium doubleheader rubber fair team rake. Error leather left fielder outs at-bat leadoff cork hit by pitch rally. Relief pitcher bleeder sidearm grounder center fielder gold glove ejection hitter foul line. Error 4-6-3 gold glove knuckleball dead ball era, save pine tar. Robbed reliever cellar alley stretch club starter leather. Red sox dead red pull no-hitter assist can of corn manager error play.</p>'
  },
  {
    title:       'Cheese Ipsum',
    category:    'food',
    author:      'El Rey de Queso',
    authorUrl:   'https://www.youtube.com/watch?v=oHg5SJYRHA0',
    publishedOn: '2015-11-02',
    body:        '<p>I love cheese, especially edam squirty cheese. Cheesecake cheese triangles boursin cheese slices airedale the big cheese st. agur blue cheese st. agur blue cheese. Fromage frais fromage frais lancashire parmesan cow chalk and cheese cow cheese on toast. Cow cheesy grin.</p><p>Melted cheese bavarian bergkase fromage frais. Blue castello cheese triangles cheese and biscuits stinking bishop paneer camembert de normandie goat cream cheese. <img src="http://lorempixel.com/400/200/" class="pull-left">Smelly cheese cheese slices stinking bishop pecorino taleggio red leicester hard cheese queso. Cow fromage chalk and cheese.</p><p>Gouda goat mozzarella. Lancashire macaroni cheese cheesecake cheese and biscuits pepper jack cow cheddar cheesy feet. Stilton cheesy grin ricotta everyone loves the big cheese squirty cheese pepper jack edam. Cheese on toast cheese and wine.</p><p>Queso camembert de normandie paneer. Parmesan bavarian bergkase feta cauliflower cheese lancashire airedale melted cheese halloumi. Who moved my cheese airedale cheese on toast cheesy feet who moved my cheese dolcelatte monterey jack fromage frais. Emmental cow.</p><p>Blue castello roquefort swiss. Cheese slices cottage cheese brie cream cheese pepper jack red leicester say cheese fromage frais. Cheesy grin cow smelly cheese camembert de normandie mozzarella cream cheese goat rubber cheese. Emmental port-salut croque monsieur boursin gouda.</p>'
  },
  {
    title:       'Hipsters Ipsum',
    category:    'lifestyle',
    author:      'Macklemore',
    authorUrl:   'https://www.youtube.com/watch?v=QK8mJJJvaes',
    publishedOn: '2015-10-28',
    body:        '<p>Freegan put a bird on it narwhal, umami marfa viral you probably haven\'t heard of them four loko kinfolk YOLO celiac echo park. <img src="http://lorempixel.com/400/300/nightlife/" class="pull-left">Viral synth fanny pack taxidermy, portland crucifix pug intelligentsia helvetica slow-carb. Venmo synth migas paleo salvia fingerstache retro, microdosing green juice pug taxidermy. Helvetica disrupt cliche you probably haven\'t heard of them mustache brooklyn. Artisan gentrify austin, hoodie portland retro yr fashion axe heirloom lumbersexual tacos messenger bag. Austin hella four loko everyday carry portland synth. Flexitarian schlitz migas yr pitchfork iPhone.</p><p>Deep v mlkshk helvetica austin PBR&B lomo raw denim blue bottle VHS cliche street art. Thundercats biodiesel craft beer cronut disrupt, tattooed ennui scenester chia deep v. Tofu +1 roof party, craft beer chicharrones ramps ugh iPhone mixtape. Vice 3 wolf moon farm-to-table chia before they sold out hammock chillwave. Deep v stumptown actually helvetica normcore chambray. Banjo scenester mumblecore gastropub church-key. Austin craft beer beard locavore wolf.</p><p>Hashtag try-hard chartreuse selvage, readymade mustache tote bag stumptown. Letterpress 3 wolf moon waistcoat small batch. Single-origin coffee williamsburg church-key, truffaut tacos yuccie stumptown synth waistcoat literally you probably haven\'t heard of them ennui. Narwhal everyday carry cardigan, vegan microdosing pitchfork flannel lomo deep v kombucha shabby chic poutine. Williamsburg VHS squid, mlkshk you probably haven\'t heard of them franzen small batch photo booth taxidermy meggings. Small batch sustainable tousled, hashtag flannel cornhole locavore polaroid lo-fi salvia helvetica franzen austin. Fixie disrupt polaroid, raw denim readymade green juice deep v scenester dreamcatcher tumblr.</p><p>Intelligentsia cray blue bottle, cardigan pinterest biodiesel ethical polaroid 8-bit master cleanse. Fap direct trade locavore, ethical shoreditch everyday carry kombucha poutine kickstarter austin. Plaid photo booth knausgaard helvetica, skateboard beard intelligentsia kitsch mixtape. Next level kinfolk farm-to-table semiotics, umami meh quinoa. Listicle viral selfies, street art kombucha squid fanny pack. Artisan XOXO heirloom, everyday carry bicycle rights lumbersexual beard roof party tattooed paleo kitsch fingerstache gluten-free. Cronut YOLO blue bottle meh, banjo skateboard vinyl austin aesthetic put a bird on it chicharrones you probably haven\'t heard of them etsy venmo direct trade.</p>'
  },
  {
    title:       'Australia Ipsum',
    category:    'travel',
    author:      'Rocko',
    authorUrl:   'https://en.wikipedia.org/wiki/Rocko%27s_Modern_Life',
    publishedOn: '2015-10-27',
    body:        '<p>Chaddie the croft institute, rooftop bars temper trap formula one grand prix frankston bogans south melb dim sims, <img src="http://lorempixel.com/300/300/nightlife/" class="pull-right">vic market aami park bill clinton ate two bowls.</p><p>Swanston the hawks, running the tan ac/dc dumplings collingwood ferals yarra, old melbourne gaol trams essendon bombers.</p><p>Four seasons in one day hipsters, etihad stadium chopper read spring racing carnival victory vs heart south of the river, brunswick and brunswick st NGV culture fix swanston.</p><p>The bulldogs temper trap, running the tan swanston north melbourne shinboners food bloggers the saints, grammar vs scotch spring racing carnival richmond tigers.</p><p>Formula one grand prix temper trap, the emerald peacock essendon bombers myki queues swanston yarra, hipsters north melbourne shinboners melbourne cricket ground.</p>'
  },
  {
    title:       'Skateboard Ipsum',
    category:    'sports',
    author:      'Rodney Mullen',
    authorUrl:   'https://www.youtube.com/watch?v=oJg2_dUHd84&t=0m1s',
    publishedOn: '2015-10-26',
    body:        '<p>Skate ipsum dolor sit amet, 270 slap maxwell pool lipslide flail. Feeble smith grind vert blunt airwalk. Casper slide Alien Workshop birdie hanger concave cess slide. Pantsman nosepicker downhill opposite footed locals impossible. Ho-ho powerslide nose Saran Wrap casper slide. Pogo powerslide vert death box Vatoland hard flip. Stoked tailslide 540 drop in launch ramp. <img src="http://lorempixel.com/350/250/sports/" class="pull-left">Slide layback slappy hanger coper. Skate or die hip boardslide nose blunt mongo. Lipslide gap impossible Santa Cruz tic-tac 720. Rip grip pogo kingpin nose-bump tuna-flip Rodney Mullen. Method air cess slide noseblunt slide salad grind stoked.</p><p>Full pipe Tracker no comply flail mINUTEMEN. Sketchy nose kick-nose powerslide Tower Skate Park. 180 kickturn stalefish no comply. Coping Kevin Harris handplant method air. Blunt slap maxwell Powell Peralta tailslide boardslide. Rick Howard boned out aerial 900 disaster. Rail slide regular footed Rick McCrank crail grab finger flip. Nose bump fast plant hospital flip switch. Rodney Mullen ollie fakie out grind manual. Lipslide nosepicker opposite footed 360. Crail slide opposite footed pogo acid drop. Fastplant Rob Roskopp stoked chicken wing nose. Kingpin axle hand rail skater.</p><p>Speed wobbles full pipe Saran Wrap hanger. Concave tail blunt axle set. Powell Peralta transition tic-tac tailslide bigspin. Kidney Sims stalefish hang up grab. Alan Gelfand lipslide soul skate skate or die poseur. Darkslide rail slide bigspin invert. Pivot yeah kickturn g-turn. Nollie baseplate ollie north 270. Fakie bigspin nose grab body varial. Berm darkslide switch slap maxwell. Varial bone air kickturn yeah. Layback nosepicker nosegrind Rick McCrank regular footed.</p><p>Japan air death box pool nosepicker. Nollie half-cab stalefish bigspin. Ollie north carve backside Transworld lipslide. Camel back rail opposite footed helipop. Air skater g-turn stalefish. Kick-nose casper mini ramp melancholy. Coper hand rail tuna-flip finger flip. Hip shinner pump feeble. Grab handplant regular footed Randy Ruiz hanger.</p><p>Hard flip 50-50 Kevin Harris noseblunt slide. Bank gnarly rad varial. Fastplant Christ air finger flip nosebone Jason Dill. Switch quarter pipe Rune Glifberg gnarly grab. Shoveit boneless chicken wing mINUTEMEN 50-50. Melancholy masonite mINUTEMEN gnarly concave. Ron Chapman poseur acid drop alley oop flypaper. Judo air 360 gnar bucket darkslide. Paul Rodriguez baseplate locals rock and roll bigspin. Coffin boneless blunt indy grab. Hurricane tail masonite Jason Wilson freestyle. Bluntslide drop in Tommy Guerrero tailslide 540. Manual steps fakie out Neal Hendrix lipslide.</p>'
  },
  {
    title:       'Batman Ipsum',
    category:    'lifestyle',
    author:      'Batman -duh',
    authorUrl:   'http://www.dccomics.com/characters/batman',
    publishedOn: '2015-10-23',
    body:        '<p>My anger outweights my guilt.</p><p>You care about justice? Look beyond your own pain, Bruce.<img src="http://lorempixel.com/300/350/people/" class="pull-left"> This city is rotting.</p><p>I\'ve sewn you up, I\'ve set your bones, but I won\'t bury you. I\'ve buried enough members in the Wayne family.</p><p>But it\'s not who you are underneath... it\'s what you do that defines you.</p><p>Didn\'t you get the memo?</p><p>There is a prison in a more ancient part of the world. A pit where men are thrown to suffer and die. But sometimes a man rises from the darkness. Sometimes, the pit sends something back.</p>'
  },
  {
    title:       'Breaking Bad Ipsum',
    category:    'television',
    author:      'Heisenburg',
    authorUrl:   'https://en.wikipedia.org/wiki/Walter_White_(Breaking_Bad)',
    publishedOn: '2015-10-21',
    body:        '<p>My partner was about to get himself shot. I intervened. He was angry because those two dealers of yours had just murdered an eleven year-old boy. Then again, maybe he thought it was you who gave the order.<img src="http://lorempixel.com/300/350/abstract/" class="pull-right"> </p><p>He has enough money to last forever. He knows he needs to keep moving. You\'ll never find him. He\'s out of the picture. I saved his life, I owed him that, but now he and I are done. Which is exactly what you wanted, isn\'t it. You\'ve always struck me as a very pragmatic man so if I may, I would like to review options with you. Of which, it seems to me you have two. </p><p>Option A, you kill me right here and now. Apparently I\'ve made that very easy for you. You can kill me, no witnesses and then spend the next few weeks or months tracking down Jesse Pinkman and you kill him too. A pointless exercise it seems to me but that is Option A. </p><p>I continue cooking, you and I both forget about Pinkman. We forget this ever happened. We consider this a lone hiccup in an otherwise long and fruitful business arrangement. I prefer Option B. </p><p>He\'ll live. I asked to see you in order to... clear the air. There are uh, some... issues that could cause a misunderstanding between us and I think it\'s in our best interest to lay the cards on the table. My brother-in-law, moments before he was attacked, someone called to warn him. I believe that same person was protecting me.</p>'
  },
  {
    title:       'Horse Ebook Ipsum',
    category:    'pets',
    author:      'Horse Whisperer',
    authorUrl:   'http://www.imdb.com/title/tt0119314/',
    publishedOn: '2015-10-17',
    body:        '<p>And practical explanations. And practical explanations. And practical explanations. And practical explanations. This is a very special technique that I have never seen. And practical explanations. This is a very special technique that I have never seen. And practical explanations. In less than three weeks you can be looking at things differently, more creatively, if you. And practical explanations.</p><p><img src="http://lorempixel.com/400/200/animals/" class="pull-left">To discourage you by telling. -And Gain Power By Learning Ways To Become Peaceful. -And Gain Power By Learning Ways To Become Peaceful. The real goal of any talk or speech. To discourage you by telling. -And Gain Power By Learning Ways To Become Peaceful. The real goal of any talk or speech. To discourage you by telling. The real goal of any talk or speech. -And Gain Power By Learning Ways To Become Peaceful. -And Gain Power By Learning Ways To Become Peaceful. The real goal of any talk or speech.</p><p>-And Gain Power By Learning Ways To Become Peaceful. Don\'t stubbornly. To discourage you by telling. To discourage you by telling. Don\'t stubbornly. Don\'t stubbornly. Space in your house How to sell faster than your neighbors How to make a strategic use. To discourage you by telling. To discourage you by telling. Don\'t stubbornly. Don\'t stubbornly. -And Gain Power By Learning Ways To Become Peaceful. Don\'t stubbornly. Don\'t stubbornly. Don\'t stubbornly. Don\'t stubbornly. Don\'t stubbornly. To discourage you by telling. Don\'t stubbornly. Don\'t stubbornly.</p><p>-And Gain Power By Learning Ways To Become Peaceful. I m going to outline 14 different ways that I ve found you. To discourage you by telling. To discourage you by telling. To discourage you by telling. Space in your house How to sell faster than your neighbors How to make a strategic use. To discourage you by telling. To discourage you by telling. To discourage you by telling. -And Gain Power By Learning Ways To Become Peaceful. The real goal of any talk or speech. To discourage you by telling.</p>'

  },
];
